services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      bash -c "
      ollama serve &
      sleep 3 &&
      ollama pull tinyllama &&
      tail -f /dev/null
      "

volumes:
  ollama_data:
